version: '3'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DUMMY=dummy
    command: /bin/bash -c "envsubst '$$DUMMY' < /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  frontend:
    build: ./frontend
    command: npm run dev
  api:
    build: ./backend
    volumes:
      - ./backend/app:/app
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./backend/.db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres