version: '3'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres