version: '3'

services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - DUMMY=dummy
    command: /bin/bash -c "envsubst '$$DUMMY' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres